### ISSUE TITLE
How to get it to work??

### ISSUE THREAD

**Issue by sootysax** [DeckerMMIV/FarmSim_Mod_SoilMod#1]
I'm a little unclear on what I need to do to get it to work.

I zipped the SoilManagement folder and put it in my mods folder.

I see that Soid Mod is loaded in my mods..  but I don't see any other evidence that is it working

I saw the Map_Instructions.txt and copied the 4 files into the root of my map mod.  Is that right?

beyond that I'm not sure what to do??  which files am I supposed to be editing and replacing or adding lines of code?

log : https://gist.github.com/sootysax/1fbc9b7edf4e7da16879/download

**Comment by DeckerMMIV** [comment]
Remember to add the 3 blocks of XML - that is shown in the Map_Instructions.txt file - to your own map.I3D file - and also replace the 4 `!!<placeholder>!!` with correct values, as instructed in the Map_Instructions.txt file.

The 4 files in the fmcSoilManagement folder, the entire folder `fmcSoilManagement` (with content) must be copied to where you have your map.I3D file. - If in doubt, then take a look at the instructions for SoilMod-FS2013, and adapt accordingly for SoilMod-FS15.

Then it should "just" be a matter of starting the map in-game. SoilMod will print problems in the LOG.TXT - so if you encounter such, then please let me have a look at your LOG.TXT from a game-session.

---

Edit:
According to your LOG.TXT, you have not added the required foliage-layers to the map:
`SoilMod: ERROR! Required foliage-layer '...' either does not exist (foliageId=nil), or have wrong num-channels (nil)`

**Comment by sootysax** [comment]
Do I have to use the Giants Editor to add the XML to the I3D file?   I've never added XML with it before...

**Comment by sootysax** [comment]
I figured out how to open the XML version of my map01.i3d

Is there a specific point where I need to insert the blocks of XML?  (at the top or bottom of the existing sections?  I assume that they need to follow the fieldId,materialiD numbers and be inserted at the bottom of each section?

**Comment by DeckerMMIV** [comment]
I have added a few notes/instructions to the [Map_Instructions.txt](https://github.com/DeckerMMIV/FarmSim_Mod_SoilMod/blob/301805a35bfa094ce0278836889fab82dd75b44b/SoilManagement/Requirements_for_your_MapI3D/Map_Instructions.txt) file.

Hope that helps.

**Comment by sootysax** [comment]
Great - very clear instructions.  Installed it into my maps and seems to be working.
