### ISSUE TITLE
Spray Types not contributing to moisture

### ISSUE THREAD

**Issue by sootysax** [DeckerMMIV/FarmSim_Mod_SoilMod#12]
My fields seem to be drying out despite using only liquid fertilizer, slurry and herbicides..  I have sprayed npk daily on all fields and herbcide cc and aa once on crop fields..  either way, should be daily adding to the moisture, but it is not...

Most noticeable on my grass fields, which are now at 0% moisture..   it is taking the fertilizer.. the N PK levels are rising, but the moisture is 0%

If I spray water, then the moisture will rise, but not with any other spray type.

**Comment by DeckerMMIV** [comment]
It may be due to the "darker texture" (i.e. spray "channel") only gets set, when there is an actual cultivated/plowed/seeded texture.

I will look into if its possible to "tweak" this.

**Comment by DeckerMMIV** [comment]
Please try v2.0.12, and inform if it fixed the problem or not.

**Comment by sootysax** [comment]
not sure if it's fixed or not..  I am seeing moisture on my grass fields from liquid NPK - and this was the major issue.. my grass fields being at 0%..   this seems to be fixed.

though crop fields is seeing no gain in moisture or a gain from 26% to 27% between growth stage 2 and 3 after spraying liquid npk. 

a drop in a sugarbeet field from 27% to 14% after spraying AA going from growth stage 1 to 2.

no change in a field going from growth stage 4 to 5 staying at 43% 

though maybe this is just compesation of plants consuming moisture and it going back from what i sprayed.

**Comment by DeckerMMIV** [comment]
On the [main page](https://github.com/DeckerMMIV/FarmSim_Mod_SoilMod) at the bottom, you can read the effects at what crop-stage it happens.
Basically the crop grows first (i.e. increases one stage), and thereafter additional effects are applied. - In your LOG.TXT you can see the order of the effects for growth-cycle;

```
SoilMod: Plugin for growth-cycle(fruits): (10) Increase crop growth
SoilMod: Plugin for growth-cycle: (15) Decrease soil pH when crop at growth-stage 5
...
SoilMod: Plugin for growth-cycle: (70) Increase/decrease soil-moisture depending on water-level
SoilMod: Plugin for growth-cycle: (71) Remove water-level
SoilMod: Plugin for growth-cycle: (79) Increase soil-moisture where there is sprayed
SoilMod: Plugin for growth-cycle: (80) Remove spray moisture
```

Also a moisture difference of less than 1/7 (14%) is most likely due to your avatar is not standing at the _exact_ same spot as previously.

**Comment by sootysax** [comment]
I thought it had rained all morning, but it wound up being hail..   shouldn't hail also contribute to soil moisture?

**Comment by DeckerMMIV** [comment]
> It rained all morning on my farm from about 7am to 1pm game time with no effect on moisture levels.
- Are you playing as;
  - singleplayer career or you are the listen-server, 
  - or as a client joining a dedicated-/listen-server?
- You sure it was 'rain' and not 'hail'? Only 'rain' will increase moisture.
- Did you see 'SoilMod %' in up-right corner starting at every hour, when the weather is 'raining'?

The other effects - i.e. those that are applied during the midnight growth-cycle - that you write about, seem correct.

**Comment by sootysax** [comment]
yeah... it was hail..   my bad
