### ISSUE TITLE
Translations - Help needed

### ISSUE THREAD

**Issue by DeckerMMIV** [DeckerMMIV/FarmSim_Mod_SoilMod#18]
I could use some help with the translations.

So if you want to contribute, find the corresponding `modDesc_l10n_<language>.xml` file, correct the "wrong words", and either send the file to me, or make a 'pull request' if you made a fork of my repository.

If a language is missing, then start making a copy from `modDesc_l10n_en.xml` and rename to the corresponding language code.

**Comment by Gonimy-Vetrom** [comment]
How to create a copy of the file for my language? I have translated Map_Instructions_ru.txt and Worksheet_for_MapI3D_ru.txt.

**Comment by DeckerMMIV** [comment]
Hmm. I didn't consider the `Map_Instructions.txt` file, but thats good someone actually thinks about that.

Though the `Worksheet_for_MapI3D.txt` is an internal work-sheet/scratch-pad file and will not be included with the mod, so it is not needed to be translated.

I guess that you, in your fork of the repository, should be able to add the new `Map_Instructions_RU.txt` file. Though please put it in a sub-folder of `Requirements_for_your_MapI3D`, something like:

```
SoilManagement \ Requirements_for_your_MapI3D \ Russian_translation \ Map_Instructions_RU.txt
```

**Comment by Gonimy-Vetrom** [comment]
I could only do so 
https://github.com/Gonimy-Vetrom/Map_Instructions-for-SoilMod/blob/master/Map_Instructions_ru.txt

**Comment by DeckerMMIV** [comment]
@Gonimy-Vetrom Ok, I've copied the file and put in the repository. _(Still wonder why it shouldn't be possible to add new file(s) to a fork-of-a-repository, and then make a pull-request.)_

**Comment by Satissis** [comment]
When browsing the files, there is an + sign after the path up top in the repository. with that one, you can create a new file :)
