### ISSUE TITLE
Zunhammer Zunidisc does not cultivate slurry?

### ISSUE THREAD

**Issue by jimerik** [DeckerMMIV/FarmSim_Mod_SoilMod#24]
hi is there a way to get the zunhammer zunidisc to cultivate the slurry down when i drive slurry at the same time. cheers

**Comment by sootysax** [comment]
#5

Edit by Decker_MMIV:
Reason is explained in https://github.com/DeckerMMIV/FarmSim_Mod_SoilMod/issues/5#issuecomment-76208374

**Comment by jimerik** [comment]
yeah i have seen that and that is ok but i would very much like the layer of slurry to go away just because it looks real

**Comment by Satissis** [comment]
@jimerik 

> yeah i have seen that and that is ok but i would very much like the layer of slurry to go away just because it looks real.

Not to sound rude, but that is actually answered why it don't work in #5 as @sootysax said, so I would read the last couple of posts again where they talk about the zundisc.

**Comment by jimerik** [comment]
thanks for the answers

**Comment by jimerik** [comment]
i have got the zunhammer to cultivate the layer away and it works with the soil,
i have open it to ge and then duplicated the workarea start, width and heigth and then i have taken the heigth of the slurry so it is rigth behind the first row of disks and the moved the start and width just behind the heigth of the slurry workarea and then moved the height of the cultivator workarea behind the last row of disks and of couse change the cultivator index the new numbers. i hope you understand what i mean and maybe it is not the best way but it works very well and with out errors in the log file
