### ISSUE TITLE
dryGrass_windrow yield

### ISSUE THREAD

**Issue by mngrazy** [DeckerMMIV/FarmSim_Mod_SoilMod#29]
hi decker

i have a test field ,,, and i have always the same dryGrass_windrow yield

mowing , tedding , swathing , baling
test 1 with soil conditions --> 6.8 / 57% / 5x / 4x = 16 bales from the field
test 2 with soil conditions --> 6.2 / 14% / 4x / 2x = 16 bales from the field

when i use a forage wagon , and i collect grass_windrow i have different yield from the field

is this a bug in soilMod or have i another problem ? ^^
i use the v2.0.25

best regards grazy

**Comment by DeckerMMIV** [comment]
Difficult to say, as `<fruit-type>_windrow` when mowed or placed by a combine (i.e. straw) is calculated differently by the base-game, than when cutting fruit.

Also the tedding and swathing may produce more or less 'windrow height' in the terrain, even when doing the same route.

Maybe when tedding, it will always produce a fixed amount of "output" (dryGrass_windrow height), no matter how much "input" (grass_windrow height) it takes?

Did you experiment with the following scenarios?:
- mowing -> tedding -> swathing -> forage wagon
- mowing -> swathing -> forage wagon
- mowing -> tedding -> forage wagon
- mowing -> forage wagon

And even then it may not give any useful diagnostics. - Maybe I need to add a console-command that can give the foliage-layer's density-value of a rectangle in the terrain.

It is not something that I will be able to "fix", as it will probably be very difficult to identify where the "problem" occurs.

**Comment by mngrazy** [comment]
i testet again with your example scenarios

always 1 lane ,,, with the 9,9m working width mower

mowing -> tedding -> swathing -> forage wagon = 23802 L
mowing -> swathing -> forage wagon = 34464 L
mowing -> tedding -> forage wagon = 27427 L
mowing -> forage wagon = 34547 L

strange thing :)

regards grazy

**Comment by Dzi4d3k** [comment]
Tedding is causing grass to dry. Dried grass have less capacity than fresh, because of less water within it.
Swathing cause grass to be torn into small pieces, which will consume less capacity for the same amount of non-swathed grass.

In my opinion everything is correct.

**Comment by DeckerMMIV** [comment]
Closing this issue.
