### ISSUE TITLE
SoilMod loads with existing Savegame, not with New Game

### ISSUE THREAD

**Issue by sootysax** [DeckerMMIV/FarmSim_Mod_SoilMod#3]
I was able to open up an existing savegame that I have with the map I installed SoilMod into.

In trying to start a new savegame with this map, SoilMod does not load.

SoilMod Beta 2.02
Map: Irgendwo_in_Thueringen (SoilMod Installed)
Map Required Mods:
zzz.multifruitmodule_standard.zip
zzz_multifruit.zip
zzz_compostSoil.zip
zzz_choppedstraw.zip
mapbuyableobject.zip
guelleMistMod.zip
CompostMaster_Transportmulde.zip
animationmaptrigger.zip

Log:
https://gist.github.com/sootysax/2b357e3567185b933ff6/download

**Comment by DeckerMMIV** [comment]
Starting a new career, should be fixed with BETA-2.0.3.

Also created a new fmcSoilMod_LayerB_density.png file, so there will be "some" nutrition and soil pH in the ground, when starting on a new map.

**Comment by mngrazy** [comment]
hi decker

the lua error is gone ,,,, all working fine when starting an new SaveGame Slot ! 

regards grazy

**Comment by sootysax** [comment]
so far for me, starting a new savegame is working on multiple maps
