### ISSUE TITLE
2.0.29 [mp] spreading NPK,PK,N increases soil moisture

### ISSUE THREAD

**Issue by vinKaiZen** [DeckerMMIV/FarmSim_Mod_SoilMod#33]
I updated from 2.0.23 to your latest files 2.0.31.

Now after spreading NPK, PK, N soil moisture increases 14% over night.
The darker moisture texture is also shown if spreaded.

But this issue is only occurs during a multiplayer session.
(the same map & same savegame in a singleplayer session do not create this issue)

Thanks for your great work on this mod!
Best regards from Germany
vin_KaiZen

**Comment by DeckerMMIV** [comment]
I assume you're using a dedicated-server (_all players are game-clients_), and not a listen-server (_one player is the game-server_.)

Unfortunately I do not have two instances of FS15 myself, to be able to debug this problem. - I will try to see if I can deduct anything from my scripts, and what they send of network-messages from the server to the clients.

But...!? You did not specify if you were using the **solid type** or the **liquid type** of NPK, PK or N.
The liquid type _will_ make the 'darker moisture texture', and this 'darker moisture texture' _will_ increase the soil moisture.
If you spread the solid type, there should not be any 'darker moisture texture'.

So what equipment did you use in both the multiplayer and singleplayer test?

**Comment by vinKaiZen** [comment]
Yes we use a dedicated server, I know that spraying the liquid fertilizer will result a moisture +. 

But in this case it´s equal if we spead NPK or PK or N (with the AMAZONE ZA-M 1501). It always adds moisture inclusive a darker texture

See my sceenshot:

http://www11.pic-upload.de/28.04.15/7tejyzsk4ki1.png

**Comment by vinKaiZen** [comment]
We have just tested the non dedicated multiplayer version (i was the host, friend joined)
If i spead NPK or PK or N (with the AMAZONE ZA-M 1501) i do not see the "darker" texture and my soil moisture value do not raise on my side. Now the funny thing: during the same time my friend see my spreading with the darker texture and his soil moisture value raises +14%

Additional test:
If he spreads he see the darker texture with the moisture raise.
And i see his spreading dry with he brighter texture without moisture raise

=> The problem occurs only client side. Hope this will help you

**Comment by vinKaiZen** [comment]
We identified file who creates the moisture issue.

It´s the **"fmcModifySprayers.lua"** up from version **2.0.29** (i can´t found the file version 2.0.28 in history)
**fmcModifySprayers.lua up to version 2.0.27 works** fine with all other files in the actual version 2.0.33
(i tried to find the error in this file buts thats to hard for me due to too much changes :P)

**Comment by Jurkkis** [comment]
I noticed it too on my dedicated server running 2.0.30. 
Did little additional test with NPK solid spreader: Spread an area-> dark texture appears, also small blue NPK particles -> Then leave the server and rejoin-> Dark texture is gone but blue particles still there.

**Comment by vinKaiZen** [comment]
@Jurkkis: i confirm your addition test.
Try newest version 2.0.33 and exchange the fmcModifySprayers.lua in version 2.0.27 until it´s fixed by DeckerMMIV

**Comment by DeckerMMIV** [comment]
I think I spotted the error. - A pure failure on my part, for not remembering to verify the number of bits required to store a value.
v2.0.34 updated with the fix.

**Comment by Jurkkis** [comment]
No problems, going to give it a test tonight.

**Comment by vinKaiZen** [comment]
**Tested. Issue #33 is fixed. Thx Decker**
