### ISSUE TITLE
Working with WheelLanes

### ISSUE THREAD

**Issue by sootysax** [DeckerMMIV/FarmSim_Mod_SoilMod#36]
So I want to implement your WheelLanes mod for ultra realism and deterrent from driving over crops..

I figure I am going to have to do all my fertilization and herbicide spraying before or just after planting if I don't want to kill crops by having to drive over them to spray.
1.  Will spraying NPK or other fertilizer or lime effect soil nutrition at the next growth cycle if there is nothing planted in the field?   Or do I have to work only with manure and slurry?
2.  What are the optimal soil / moisture/ pH levels I should achieve at the time of planting if I want my harvest levels to be at 100% when crop reaches maturity without driving over the crop / spraying at all during growth.

**Comment by DeckerMMIV** [comment]
_Please put any questions/issues regarding my WheelLanes mod, in the [WheelLanes repository](https://github.com/DeckerMMIV/FarmSim_Mod_WheelLanes)_
1. Yes it will - and - No, you are not restricted to only manure/slurry.
2. Check [my response on FS-UK](http://fs-uk.com/forum/index.php?topic=172152.msg1154724#msg1154724) for the same question.
