### ISSUE TITLE
filltypeOverlays

### ISSUE THREAD

**Issue by litlebuda** [DeckerMMIV/FarmSim_Mod_SoilMod#40]
Hi .

I´m having this error :
Error: Can't load resource 'C:/Users/Litlebuda/Documents/My Games/FarmingSimulator2015/mods//DondiegoMapReloadet/../SoilManagement/filltypeOverlays/kalk.dds'.
Error: Can't load resource 'C:/Users/Litlebuda/Documents/My Games/FarmingSimulator2015/mods//DondiegoMapReloadet/../SoilManagement/filltypeOverlays/fertilizer2b.dds'.
Error: Can't load resource 'C:/Users/Litlebuda/Documents/My Games/FarmingSimulator2015/mods//DondiegoMapReloadet/../SoilManagement/filltypeOverlays/fertilizer3b.dds'.
Error: Can't load resource 'C:/Users/Litlebuda/Documents/My Games/FarmingSimulator2015/mods//DondiegoMapReloadet/../SoilManagement/filltypeOverlays/herbicide1.dds'.
Error: Can't load resource 'C:/Users/Litlebuda/Documents/My Games/FarmingSimulator2015/mods//DondiegoMapReloadet/../SoilManagement/filltypeOverlays/herbicide2.dds'.
Error: Can't load resource 'C:/Users/Litlebuda/Documents/My Games/FarmingSimulator2015/mods//DondiegoMapReloadet/../SoilManagement/filltypeOverlays/herbicide3.dds'.
Error: Can't load resource 'C:/Users/Litlebuda/Documents/My Games/FarmingSimulator2015/mods//DondiegoMapReloadet/../SoilManagement/filltypeOverlays/herbicide4.dds'.
Error: Can't load resource 'C:/Users/Litlebuda/Documents/My Games/FarmingSimulator2015/mods//DondiegoMapReloadet/../SoilManagement/filltypeOverlays/herbicide5.dds'.
Error: Can't load resource 'C:/Users/Litlebuda/Documents/My Games/FarmingSimulator2015/mods//DondiegoMapReloadet/../SoilManagement/filltypeOverlays/herbicide6.dds'.

I´m lost , because i do not know where should these ovelays be . 
Could you please point me in the right direction ?

Thanks

**Comment by mngrazy** [comment]
have you the SoilMangement.zip extractet in your map ? thats wrong !
the SoilManagement.zip comes in the Mod Directory only !

regards grazy

**Comment by litlebuda** [comment]
@mngrazy 

No . In my map I have only fmcSoilManagement .

I just noticed this after updating the game with patch 1.3 Beta .

**Comment by litlebuda** [comment]
Found it  !

The problem was only me :)
