### ISSUE TITLE
Fast growing cover crops

### ISSUE THREAD

**Issue by sootysax** [DeckerMMIV/FarmSim_Mod_SoilMod#42]
Crops, from 2nd growth and up to withered (growth stages 3-8);
when plowed adds; +5 N, +1 PK
when cultivated adds; +2 NCrops, from 2nd growth and up to withered (growth stages 3-8);
when plowed adds; +5 N, +1 PK
when cultivated adds; +2 N

Should the above (growth stages 3 and above) have an exception for supposedly fast growing cover crops like alfalfa and clover??

Perhaps being able to plow them under sooner than other crops.

**Comment by DeckerMMIV** [comment]
Are the `alfalfa` and `clover` fruit-types and their corresponding foliage-sub-layer, actually set up to grow faster than crops like wheat or potato?

**Comment by sootysax** [comment]
i will have to experiment with that

**Comment by DeckerMMIV** [comment]
Closing this issue, due to no further information.
