### ISSUE TITLE
Too much raise of N level when cultivating crops 

### ISSUE THREAD

**Issue by Laui51** [DeckerMMIV/FarmSim_Mod_SoilMod#43]
Hey Decker,

i'm playing the MIG Map Soilmod beta (which can be found here http://uploaded.net/file/y47zlpcs ).

When i cultivate any crop or manure it gives a much higher rise of the N Level than it should be, from what i tried so far about 10 points. Is there anything i could do wrong to force that, that you are already aware of?

I tested other maps but couldn't find that again. I saw that User Last2Night mentioned something similar at the support topic.

Thanks for any ideas. 

Stefan

**Comment by DeckerMMIV** [comment]
Maybe it is due to wrongly sized .GRLE width/height. The `fruit_density.grle` file's width/height must be the same as the two `fmcSoilMod_Layer*_density.grle` files (or vise versa)

I'm not going to download that map of that site (_will take me hours upon hours_), so can't check myself.

**Comment by Laui51** [comment]
Jap, the sizes where different. It's a big map (x4), that will be the reason. 

Thanks for your help and have nice weekend!
