### ISSUE TITLE
Sowing with fertilizer clover, alfalfa and canola as a catch crop

### ISSUE THREAD

**Issue by Paul2510** [DeckerMMIV/FarmSim_Mod_SoilMod#46]
Hello! Could you as the slurry manure lime mod a way the man with fertilizer clover, alfalfa and canola can sow catch crops?
LG

**Comment by DeckerMMIV** [comment]
Seems like there was some translations problems from your native language to English, but I hope I got your question correct:

_"Is it possible to use clover, alfalfa & canola to use as fertilization, before the next crop is seeded?"_

My answer:
Yes, and it is already implemented in SoilMod. If you let the crops grow or even become withered, then you can;
- cultivate to increase N by +2,
- plow to increase N by +5 and PK by +1.

It is mentioned as the first item in the [list of effects](https://github.com/DeckerMMIV/FarmSim_Mod_SoilMod#effects)

I do not know what effects the GülleMistKalk mod introduces regarding this. Actually I'm convinced that it is upsidedown's [Green Manure](http://www.modhoster.com/mods/grundunger) mod that has this effect - which probably will conflict with SoilMod.

**Comment by Paul2510** [comment]
I'm sorry for my english! I meant clover and Lucerne seed with the fertilizer spreader!

**Comment by DeckerMMIV** [comment]
Uhm? You want to spread seeds with a fertilizer spreader? I have never seen that in a mod.

It will not work with SoilMod, as `seeds` is not a spray-type that SoilMod will add to spreader/sprayer equipment.

**Comment by Paul2510** [comment]
The GMK-Mod has a function that you sow alfalfa, clover and rape as a catch crop can!

**Comment by DeckerMMIV** [comment]
I looked up Wikipedia's definition of [catch crop](http://en.wikipedia.org/wiki/Catch_crop), and then the [succession planting](http://en.wikipedia.org/wiki/Succession_planting).

As explained earlier, SoilMod already have the ability to cultivate/plow grown crops, to increase N/PK. - i.e. "_.. between successive plantings of a main crop._" and "_Two or more crops in succession_."

But are you really asking for; having two _simultaneously seeded_ crops, like clover **and** rape in the same field at the same time? - I.e. "_fast-growing crop that is grown simultaneously with [..] the main crop._" and "_Two or more crops simultaneously_."

If the latter is the case, then SoilMod has no support for it.

Also it would require a secondary `<FoliageMultiLayer>` to contain the clover, alfalfa, lucerne, etc. crops. And having multiple FoliageMultiLayers for crops will probably cause other problems elsewhere.

Not that it is impossible, just difficult to figure out how it should be structured in the map.i3d file and coded in the LUA-scripts.

**Comment by Paul2510** [comment]
No sorry! I mean sow crops with fertilizer spreader!

**Comment by DeckerMMIV** [comment]
So something like what Wikipedia describes as a 'Broadcast spreader':
http://en.wikipedia.org/wiki/Broadcast_spreader
http://de.wikipedia.org/wiki/D%C3%BCngerstreuer _(I don't understand that language)_

Hmm. Maybe it could be possible.

So 'solid fertilizer' spreader equipment, like the Amazone ZAM 1501 and the Amazone ZGB 8200, filled with 'clover'-seeds (or other predefined/hardcoded fruit-type), will act as a sowing-machine.

One problem though. Most sowing-machine works with 'direct drilling', so any existing (cutted-)crops that is on the field, will be "cultivated away", as there can _only be one fruit-type_ at any given time in a square in a field.

So how should such a 'broadcast spreader' act within FS15? That is;
- when spreading 'clover' on a field that already has crops growing, should it...
  - remove the existing crops and place down the 'clover' (_not realistic_), or
  - not place any 'clover', as the existing crops must never be removed (_a bit more realistic_).

Oh, another problem: What fruit-types are allowed to be used in this 'broadcast spreader'? - Should 'wheat', 'barley', 'maize', 'rape', 'sugarBeet', 'potato' be allowed to be spread with it too?

**Comment by Paul2510** [comment]
So if only rape, lucern and klee! The field should be processed before the field! e.g. cultivators! Then sow the catch crop then plow!

**Comment by jimerik** [comment]
i like some of the ideas in here, and this (remove the existing crops and place down the 'clover' (not realistic),) could be realistic because here in denmark there are many there uses after crop to gain the earth some good stuff to the next crop and with this i think it could be done so a cultivator with a seedbox on top could seed the crop and then it was grown maybe in 2 growthstages and then you cultivate or plough it to gain the effectand here you have some pics that shows how the crop is looking like, and there is pics of how it being sowed. ( https://www.google.dk/search?q=efterafgr%C3%B8der&biw=1920&bih=955&tbm=isch&tbo=u&source=univ&sa=X&ved=0CDEQsARqFQoTCPOu1_CJh8YCFfMI2wodW88AlQ#imgrc=YS8wtRE-hUzE6M%253A%3BSwVqWgSBgRmlxM%3Bhttps%253A%252F%252Fwww.landbrugsinfo.dk%252FTvaerfaglige-emner%252FFarmTest%252FPublishingImages%252Fc8b5bd33b85c467980e7f093b0f3db4b.jpg%3Bhttps%253A%252F%252Fwww.landbrugsinfo.dk%252Ftvaerfaglige-emner%252Ffarmtest%252Fmaskiner-og-planteavl%252Fsider%252Ffarmtest__etablering_af_efterafgroeder_m.aspx%3B350%3B263

**Comment by Paul2510** [comment]
If I understand correctly you mean a undersowing? That would be the very best!

**Comment by jimerik** [comment]
if you mean what i mean then it is when you have harvestet an field then drive over with a cutivator with an seedbox on the top that seeds the crop to get better dirt for the next crop
