### ISSUE TITLE
When start new game have valor 5.1 pH

### ISSUE THREAD

**Issue by Vanquish081** [DeckerMMIV/FarmSim_Mod_SoilMod#47]
I have not changed anything on the map, just fix the ground for patch 1.3 and now every time I start a game pH values are 5.1-5.8 besides not appear any value in moisture and nutrients. This map is x4.

P.D.: Change the file moddesc_l10n_es in next version for this:
https://www.dropbox.com/s/c9zif0vqcwyf6ey/modDesc_l10n_es.xml?dl=0

**Comment by DeckerMMIV** [comment]
Have you remembered to resize the two `fmcSoilMod_Layer*_density.grle` files, so they have the same width/height as your `fruit_density.grle` file?

If you are unhappy with the starting soil values, you can use the console-command `modSoilModPaint` (_before v2.0.44 it was named `modSoilMod`_) to "paint" either a correctly defined field with field-borders, or the whole 'world'.
See [this post](https://github.com/DeckerMMIV/FarmSim_Mod_SoilMod/issues/34#issuecomment-97912568) for the syntax of the `modSoilModPaint` console-command (previously named `modSoilMod`.)

When you have "painted" the world in-game, and saved your game, you can then copy the savegame's two GRLE files back into your map-mod.

Thank you for the updated ES translations. I will include them next time I commit.

**Comment by Vanquish081** [comment]
the density.grle files have the same size that fruit_density

Ok, is solved with use the console-command and photoshop for fully paint.
