### ISSUE TITLE
Field borders definition when using modSoilModPaint command

### ISSUE THREAD

**Issue by PromGames** [DeckerMMIV/FarmSim_Mod_SoilMod#52]
@DeckerMMIV , I was using the console command that you define and it is very useful.

If the field borders are correctly defined in the i3d file, then is working ok, but that is not the case usually 

Normally, the borders for a irregular field is quite difficult to define, but we have that data already scanned by two other programs, field status and courseplay. 

Just a suggestion, would be possible to calculate fields extensions in the same way that courseplay or field status is doing, based on the actual hedge of the field and not the information that appears in the i3d. Then we will paint all the extension af that field and just the tension defined in the i3d.

Thanks for your work. 

PromGames

**Comment by DeckerMMIV** [comment]
No, I have no intentions of attempting to have something like that added, as the `modSoilModPaint` console-command is only a "debug / testing tool", and not to be used by players nor map-makers per se.
