### ISSUE TITLE
Stacking fertilizer's?

### ISSUE THREAD

**Issue by jhomer** [DeckerMMIV/FarmSim_Mod_SoilMod#54]
I know there is mention of not being able to stack multiple fertilizer's at the same growth cycle.
Not sure if this just applies to Soil Mod's spray types or if it's all types that add any value increase to "N" or PK"?

The reason I bring this up is that I tried adding compost_soil on top of a chopped_straw layer and then plowed. The result was just an increase of 1 "N" and 1 "PK". The soil was darker where the compost was but had no effect on N or PK. Even after a "grow now" cycle was complete- the values did not change.

I apologize if this had already been mentioned.

**Comment by DeckerMMIV** [comment]
- What version of SoilMod are you using?
- What other possible conflicting mods do you have in your MODS folder?
  -- _Plowing compost or any of the 3 chopped straw types, should not produce 'darker texture'. (Or did you spray some liquid before plowing?)_

Please remember, that there is a max-limit to what the N and PK levels can be. N can not get higher than x15, and PK no higher than x7.

**Comment by jhomer** [comment]
Using 2.0.47
As for mods, I can't think of any that would conflict but if no one else has experienced this then it must be on my end.

I started with 4 N and 4 PK. Added compost (with spreader) on top of chopped straw, then plowed.
The result was 5 N and 5 PK for both the chopped straw and chopped straw/ compost, with a darkened area where the compost was. I did use your "grow now" feature instead of the time passing.

Looks like I'll have to do more testing and re-post with the result.
Thanks for the quick response!

I should note that it was soybean that was the "chopped straw" but from the values it seems the compost was not responding.
Also, no sprays of any kind were used, just the chopped and compost.

**Comment by jhomer** [comment]
So I finally tried this again:
This was on a plowed field with nothing else on it,
1- Spread compost which added the dark "wet" texture (not sure if this is correct).
2- Plowing had no effect on any of the values.
3- Day advance created a 14% moisture increase but no fertilizer increase.

Not sure what kind of mod could cause problems?
I have the ZZZ_compost mod which creates the spray type.
Using a modded spreader that has the fill and spray types of manure and compost_soil.
Also using the ZZZ_multiFruit mod and tried taking out the configuration multiFruit conversion for compost_soil with no different result.

**Comment by DeckerMMIV** [comment]
> I have the ZZZ_compost mod which creates the spray type.

That mod is probably what causes the dark "wet" texture.

Could you put your LOG.TXT file from a game-session on https://gist.github.com so I can have a look at what mods and possible other warnings/errors there may be?

**Comment by jhomer** [comment]
https://gist.github.com/jhomer/3e329a5dd9c4a7454fa3

The log is mostly clean other than unzipped mods not for multiplayer and 
a bunch of static actor moved warnings- have about 10 pivot irrigators on the map and this was my best result to make them have no collision and still work, other than these errors. 

Isn't the ZZZ_compost mod still needed? I tried taking it out and went in game and the spreader that was filled with compost was empty. This was the lua. that came with the mod.

I have no troubles with any other part of soil mod except for this.

Tried one more time---
-Spread compost- created dark texture
-plow- no change except for day advance there was no moisture increase where plowed
     (I think plowing brings moisture down 14%)
-where not plowed- day advance- moisture increased 14%

**Comment by jhomer** [comment]
I have now figured it out!!
After doing a lot of research:

I did not have a foliage layer for compost_soil.
-Added the foliage layer
-Then I could not figure out why it wouldn't paint in GE 
-I didn't know what a densityMapId was
-I then found on the giants website someone asked what a densityMapId was
-The answer to that persons question came from the one and only @DeckerMMIV !!!
-With your explanation there, I now have a working compost_soil

Thanks for the "past" and present help!!
