### ISSUE TITLE
Wheel Lanes and plowing cover crops

### ISSUE THREAD

**Issue by sootysax** [DeckerMMIV/FarmSim_Mod_SoilMod#57]
Wondering if there is a work around for using a plow to plow withered crops as fertilizer and using wheel lanes..  

In order to plow the crop into the ground, you need to drive over it, destroying the crop before your plow reaches it...   this results in about a +2N in the soil rather than +5N if there was no crop destruction...

I can disable wheel lanes when I want to plow a cover crop..  but hoping there is a tweak that can be made.  Perhaps making the same exception for withered crops as with grass/alfalfa/luzerne/clover.

**Comment by DeckerMMIV** [comment]
Looks like this 'issue' belongs to my [WheelLanes](https://github.com/DeckerMMIV/FarmSim_Mod_WheelLanes) mod, and not my SoilMod mod.
