### ISSUE TITLE
Be able to see what has been spread...

### ISSUE THREAD

**Issue by sootysax** [DeckerMMIV/FarmSim_Mod_SoilMod#7]
In the FS13 version, you were able to see which fertilizer was already on the soil when you drove over it..   will that be implemented or was it removed for not being realistic..

Aside from keeping a work log, once the soil is wet, you dont know what has been added or not..

oh, i do see that you can see what herbicide has been sprayed..  this is helpful, never mind

**Comment by DeckerMMIV** [comment]
The 3 fertilizer types actually have foliage-graphics if you look closely at the ground.

The solid-fertilizers are more visible than the liquid-fertilizers.

Though once the growth-cycle have run, the fertilizers have been converted into the nutrition N and PK layers.
