### ISSUE TITLE
Possibility of having soil mod as an add on

### ISSUE THREAD

**Issue by PromGames** [DeckerMMIV/FarmSim_Mod_SoilMod#74]
Hi Decker,

I was wondering if would be possible to have the soil mod as an add on on the new map from the gold edition. I think going through an add on basis, we are not breaking any copyrights from Giants.

I have installed the storage add on from pinguar and is very interesting how he is able to include data in the new map, and also add and replace data in the original map.

If we go through the map installation instructions, we need to include files in the map, that is not possible and also folders. But if you do as an add on, the files could be Located in the mod folder. I do not know if this will work.

Also we need to add materials (pinguar do it very easy)

But the replacement of the multilayer is the more difficult part as we need to override the data from the original map and know exactly what are the original numbers. 

Would be nice to have soil mod on the new map, but may be is not possible. If you feel that could be done, I will be very happy to help and test.

Regards

**Comment by DeckerMMIV** [comment]
I anticipated such a question/request, and all I can say is that it depends on GIANTS.

Please see my request at GDN: https://gdn.giants-software.com/thread.php?categoryId=20&threadId=3171
I can not do more at this time, until GIANTS adds some kind of support for that.
