### ISSUE TITLE
crops growing crosses on fields

### ISSUE THREAD

**Issue by NOR3MSTI** [DeckerMMIV/FarmSim_Mod_SoilMod#76]
First of all great mod, I had this same issue with another map where the crops would grow crosses in the fields, lines horizontal and diagonal, the growth would be more than the planted, I fixed this by recreating the grle file, my question; is there an easier way to fix this because I will have to re plant all the grass and crops, and it's a 4x map, just making sure there isn't an easier fix than doing that.
thanks

**Comment by DeckerMMIV** [comment]
The reason for these "crosses" or "squares / boxes", is most likely that the following .GRLE files does not have the same width/height:
- fruit_density.GRLE
- fmcSoilMod_LayerA_density.GRLE
- fmcSoilMod_LayerB_density.GRLE

I.e. if the fruit_density.GRLE file is at 4096 x 4096, then the other two .GRLE files must also be resized to that same width & height.

**Comment by NOR3MSTI** [comment]
ok, i was able to do that but they were already the correct size, any other suggestion?

**Comment by NOR3MSTI** [comment]
ok, nevermind i need the converter, again thanks for this mod and keep up the good work

**Comment by Dzi4d3k** [comment]
Another cause is interrupting game when SoilMod works. Few days ago we got such effect after stopping dedicated server around 12:00 o'clock (in game time) in hot day. After that we have calculated and uncalculated squares on owned fields.

**Comment by DeckerMMIV** [comment]
@NOR3MSTI 
I have no other suggestions. 

@Dzi4d3k 
Was that a "small lines / grid-line / crosses"-pattern or a ["checkerboard"-pattern](http://fs-uk.com/forum/index.php?topic=172152.msg1181945#msg1181945) effect?

**Comment by Dzi4d3k** [comment]
A  "checkerboard"-pattern and only on fields on which we made work steps in morning that in game day.
