### ISSUE TITLE
Fertilizer Fill Type?

### ISSUE THREAD

**Issue by sootysax** [DeckerMMIV/FarmSim_Mod_SoilMod#8]
I know this also was an issue when SoilMod first came out for FS13.  Is there any way for you to adjust SoilMod to allow the sprayer/spreader to lock onto a fertilizer/herbicide type and allow it to fill from the fertilizer trigger when set to a different type.

As it stands, it will automatically switch back to NPK if it is empty when refilling, or if there is anything left in the tank, will not refill until you switch back to NPK.

This is especially important for Courseplay users who want to have a refill course and go back to the field to resume spraying where it left off..    Works with NPK, but not when using other types.

I know the work around is to wait for someone to convert the placeable fill triggers...   but not sure you have the info out there yet for them to do so.

**Comment by DeckerMMIV** [comment]
The game's base scripts seem to force the fill-type to 'fertilizer' (the one I've change icon to "NPK" for), so unfortunately I can not do much about that.

I have not yet studied if it is the sprayer-fill-trigger (fertilizer tank's script) or it is the sprayer script that does this.

You could try to "convert" the placeable fill triggers yourself. If there already exist placeable 'fertilizer tanks' for FS15, then I guess it should "just" be a matter of changing its fill-type to one of SoilMod-FS15's.

**Comment by sootysax** [comment]
I've reached out to the guy who created the Placeables for FS13 and see if he would convert those for FS15.

I suppose the Sprayer and Additional tank are not set up to be filled from the water trigger for filling with water, so an additional placeable would have to be developed for water as well.

**Comment by DeckerMMIV** [comment]
Closing this issue, as having placeable fill-triggers with the corresponding fill-type seem to be a work-around for this.
