### ISSUE TITLE
Lime in sprayers

### ISSUE THREAD

**Issue by Pitufo306** [DeckerMMIV/FarmSim_Mod_SoilMod#81]
Good night, think of a problem with the latest version, when switching between products on the liquid spray, lime appears me. As I can fix that? I am using the original spray the game. A greeting!!

**Comment by DeckerMMIV** [comment]
Could you please upload your LOG.TXT file, from a game-session where you experience the problem.

Either use https://gist.github.com/ or a 'paste-bin' website, to place the LOG.TXT at - then post the link here.

It could be due to another mod you have in your MODS folder, that adds 'kalk' (lime) to all Sprayer-tools.

**Comment by Dzi4d3k** [comment]
Hi,

I think that Pitufo306 is referring to situation, where lime (kalk) fill type is available for selection in sprayers as on following screenshoot:

![fsscreen_2016_01_31_14_48_39](https://cloud.githubusercontent.com/assets/12050055/12760751/379378c8-c9e8-11e5-8f46-ebc4905d190f.png)

In my case I've removed GMK (GMM) mod from map, in the terms of foliage layers and register script. Maybe I've missed something.

Edit: Tested on version 2.2.6 with recent changes about sprayer fill types.

Regards.

**Comment by DeckerMMIV** [comment]
There must be some other mod you both use, or maybe it is embedded into the map-mod you're using, which adds 'kalk' to all Sprayer-tools.

Have you added 'kalk' using the multifruit mod? - If yes, then that could also be the problem.

Please experiment with emptying your entire MODS folder, and put in the map-mod and SoilMod as the _only 2 mods_. - If you are still able to choose 'kalk' for a liquid sprayer tool, with only these two mods in your MODS folder, then please study the map-mod's scripts.

---

(Uhm? "-50" in top right corner). - Are you having this 'kalk' problem only in multiplayer and/or in singleplayer?

**Comment by jefferyharrell** [comment]
I'm very late to this, but in case it's still an outstanding issue: If you use just have the Multifruit script mod _installed_ alongside SoilMod it'll auto-add lime to all fertilizer sprayers. This can be easily disabled, though. Inside ZZZ_multiFruitModule_Standard.zip there's an XML called multiFruit_config.xml. Comment out this line…

```
<multiFruit new="kalk" subStd="fertilizer" subCutter="fertilizer" subSowing="fertilizer"/>
```

…and sprayers will revert to the correct NPK/N/PK/A/B/C/AA/BB/CC/💧/☠️ selection.
