### ISSUE TITLE
fruitHuds dont load from inside the map (v2.2.9)

### ISSUE THREAD

**Issue by mngrazy** [DeckerMMIV/FarmSim_Mod_SoilMod#88]
hi decker

small issue with the new version 2.2.9

i have a own "fruitHud" for lime (kalk)  in my map
its working with the v2.2.6 , but not with the v2.2.9

can you check this pls ? :)

best regards grazy

**Comment by DeckerMMIV** [comment]
Please check to see if it is fixed now.

**Comment by DeckerMMIV** [comment]
Oh BTW. - If Pandahma still have not understood how to use custom map "fruitHud" icons in his Norgeholm map, could you perhaps please instruct/help him to do so? :wink: 

I really would hate to see him modifying & distributing an unofficial SoilManagement.ZIP again, once I release a new one.

**Comment by mngrazy** [comment]
the fruitHuds from inside the map are working now with 2.2.10 ,,, thx decker

i try it with Pandahma ,,, we are not the best friends :P 

best regards grazy
