### ISSUE TITLE
Folder FruitMaterial?

### ISSUE THREAD

**Issue by Lonegan16** [DeckerMMIV/FarmSim_Mod_SoilMod#89]
Hi,

Could someone explain what function this folder and its contents?

Thanks!!

**Comment by Gonimy-Vetrom** [comment]
http://fs-uk.com/forum/index.php?topic=180119.msg1209314#msg1209314

**Comment by DeckerMMIV** [comment]
@Lonegan16 
If you do not already know of what 'fill-plane materials' are used for when making your own mods, then you do not need to worry with SoilMod's content.

---

For more information;
- https://forum.giants-software.com/viewtopic.php?t=81950
- https://forum.giants-software.com/viewtopic.php?t=83998

**Comment by Lonegan16** [comment]
Now I understand perfectly.

Thank you very much for your help!!

regards
