### ISSUE TITLE
Additional Spray Tank FT1001 Bug

### ISSUE THREAD

**Issue by sootysax** [DeckerMMIV/FarmSim_Mod_SoilMod#9]
The additional spray tank Amazone FT1001 is not working correctly.   When the UF1801 sprayer runs empty, and it switches over to the additional tank, the spray is not effecting the field soil (in this case, Herbicide type CC).   When I chase the tank on foot, the information in the SoilMod display indicates no Herbicide type or days of weed prevention once the sprayer switches to the additional tank.

Both tanks were filled and both are changed to Herbicide CC.  

The Glance mod shows that I am spraying Herbicide CC while both tanks are being emptied.

I am not sure if this is also the case with the NPK that I sprayed earlier on the field (or if the additional tank is outputting NPK instead of Herbicide CC).   I guess I will have to wait for the growth stage and see if there are sections that are not fertilized (or sprayed twice with NPK) where the sprayer switched tanks.

**Comment by DeckerMMIV** [comment]
Please try BETA-2.0.10, and tell me if it works or not.

**Comment by sootysax** [comment]
Does the fmcsoilmanagement folder need to be replaced in the map folder each time a beta is released?

**Comment by DeckerMMIV** [comment]
Not unless there's changes in it, which will be mentioned in the commit note.

**Comment by sootysax** [comment]
Looks like the additional tank is now working...  thanks!
