### ISSUE TITLE
Fertilizer "Multiplier"

### ISSUE THREAD

**Issue by ghost** [DeckerMMIV/FarmSim_Mod_SoilMod#90]
Ok here is my idea to make it less work intensive and more realistic. 
My idea is to implement the possibility to change the multiplikator when fertilizing. For Example: 
NPK brings you 3N and 1PK, but you need 6N and 2PK. So now you can multiply it with 2. That means fertilizing with NPK brings you 6N and 2PK but also you consume twice as much fertilizer. That is a real thing which every farmer does. He looks to the values from the field and with this in mind he choose his Fertilizer Consumption per sqm. 

Hope you understand what i mean :)  

Edit: If thats not possible or planned, it's possible that i can change the values to my likings?

**Comment by DeckerMMIV** [comment]
Unfortunately that is currently not possible, as making "specialized" fertilizer effects would either;
- cause the exact same effect to occur to the entire map and all its fields during the growth-cycle,
- or require many more foliage-sub-layer channels, to distinguish each specialized fertilizer "type".

If you look into the script-code, there are places where these values can be changed - but again, this will affect the entire map and all fields during growth-cycles.

**Comment by ghost** [comment]
Ok that's sad to hear ;). Anyway where can i find these Values?

**Comment by DeckerMMIV** [comment]
Search for `Increase N where there is` and `Increase PK where there is`.
